# -*- coding: utf-8 -*-
"""url-shortener-project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQKWMQmNxaouAhDpt7dkwmeYun7SHVPJ
"""

!pip install pyshorteners

import pyshorteners

# Function to shorten a URL
def shorten_url(long_url):
    try:
        shortener = pyshorteners.Shortener()
        return shortener.tinyurl.short(long_url)
    except Exception as e:
        return f"Error: {e}"

# Main program
print("Welcome to the URL Shortener!")
long_url = input("Enter the URL to shorten: ")
short_url = shorten_url(long_url)
print(f"Shortened URL: {short_url}")